// Render actual built/deployed assets with isolated room fixtures. Never changes production data.
// npm install --no-save playwright; npx playwright install chromium webkit; node tests/shoug-screen.cjs
const {chromium,webkit}=require('playwright'),{execFileSync}=require('node:child_process');
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const build=path.resolve(__dirname,'../build');
const corpus=JSON.parse(execFileSync('python',['-c',`import importlib.util,json
s=importlib.util.spec_from_file_location('shoug',${JSON.stringify(path.resolve(__dirname,'../../backend/import_shougs_tale.py'))})
m=importlib.util.module_from_spec(s);s.loader.exec_module(m)
print(json.dumps(m.build_graph()))`],{encoding:'utf8'}));
const keys=new Set(['001','003','010','044','063','066','072','090','095','102','104R']);
for(const score of [n=>n.story_text.length,n=>n.title.length,n=>n.choices[0]?.text.length||0,n=>n.choices[1]?.text.length||0,n=>n.story_text.length+n.choices.reduce((v,c)=>v+c.text.length,0)])keys.add(Object.keys(corpus).sort((a,b)=>score(corpus[b])-score(corpus[a]))[0]);
const sizes=[['small-iPhone',320,568,20,34],['modern-iPhone',390,844,47,34],['small-Android',360,640,24,24],['Honor-Android',412,892,24,24]],results=[];
(async()=>{
const server=http.createServer((req,res)=>{let f=path.join(build,new URL(req.url,'http://localhost').pathname);if(!fs.existsSync(f)||fs.statSync(f).isDirectory())f=path.join(build,'index.html');res.setHeader('Content-Type',f.endsWith('.js')?'application/javascript':f.endsWith('.css')?'text/css':f.endsWith('.json')?'application/json':'text/html');res.end(fs.readFileSync(f));});
if(!process.env.SHOUG_TEST_URL)await new Promise(r=>server.listen(4174,'127.0.0.1',r));const url=process.env.SHOUG_TEST_URL||'http://127.0.0.1:4174';
try{for(const type of(process.env.SHOUG_ENGINE==='chromium'?[chromium]:[chromium,webkit])){
console.log('engine',type.name());const proxyURL=process.env.SHOUG_TEST_URL&&process.env.HTTPS_PROXY?new URL(process.env.HTTPS_PROXY):null;const browser=await type.launch({headless:true,...(proxyURL?{proxy:{server:proxyURL.origin,username:decodeURIComponent(proxyURL.username),password:decodeURIComponent(proxyURL.password)}}:{}),...(type===chromium&&process.env.SHOUG_CHROMIUM?{executablePath:process.env.SHOUG_CHROMIUM}:{})});
for(const[device,width,height,top,bottom]of sizes){
console.log('viewport',device);const context=await browser.newContext({viewport:{width,height},isMobile:true,hasTouch:true,serviceWorkers:'block'}),page=await context.newPage();page.setDefaultTimeout(15000);let state,socket;
await context.addInitScript(()=>localStorage.setItem('player_TEST',JSON.stringify({id:'p',is_host:true,nickname:'Layout test'})));
// Shoug is local/system type; exercise offline font-CDN behavior without unrelated homepage font requests stalling WebKit.
await page.route('https://fonts.googleapis.com/**',r=>r.abort());await page.route('https://fonts.gstatic.com/**',r=>r.abort());
await page.route('**/api/rooms/TEST',r=>r.fulfill({json:state}));await page.routeWebSocket(/\/api\/ws\/rooms\/TEST/,ws=>{socket=ws;ws.send(JSON.stringify({type:'room_state',state}));});
for(const key of keys){const n=corpus[key];state={story:{title:'Shoug’s Tale'},current_node:{...n,id:`node-${key}`},choices:n.choices.map((c,i)=>({...c,id:`c${i}`})),room:{started:true,phase:n.is_end?'ended':'voting',flags:['PHONE_SAFE','SHAHEEN_CLOSENESS','SHAHEEN_TRUST','SHOUG_TRUST','FAMILY_HEAT','BICESTER_CARD','SHOMOUKH_SECRET','SHOMOUKH_WAR','RARE_KINDNESS','RARE_ROUTE','MATCHA_PHOTO'],phase_ends_at:new Date(Date.now()+20000).toISOString()},players:[{id:'p',is_host:true}],vote_stats:{voted_count:0,total_players:1,voted_player_ids:[]}};
if(!socket){await page.goto(`${url}/play/TEST`,{waitUntil:'domcontentloaded'});await page.locator('.shoug-canvas').waitFor();await page.addStyleTag({content:`.shoug-canvas{padding-top:${top}px!important;padding-bottom:${bottom}px!important}`});}else socket.send(JSON.stringify({type:'room_state',state}));
await page.waitForFunction(t=>document.querySelector('.player-story-text')?.textContent===t,n.story_text);await page.waitForTimeout(350);
for(const locked of[false,true]){if(locked){state={...state,vote_stats:{voted_count:1,total_players:1,voted_player_ids:['p']}};socket.send(JSON.stringify({type:'room_state',state}));await page.waitForTimeout(150);}
const audit=await page.evaluate(()=>{const root=document.querySelector('.shoug-canvas');const bands=[...root.querySelectorAll('.shoug-scene-header,.player-story-card,.shoug-choice,.player-dock')].map(e=>({band:e.dataset.shougBand,pair:e.dataset.shougPair}));
const required=[...root.querySelectorAll('.player-story-text,.shoug-scene-header strong,.shoug-choice,.player-choice-text,.player-choice-state,.player-dock,.player-vote-count,.player-progress,.player-primary-button,.player-secondary-button')];
const over=required.map(e=>{const b=e.getBoundingClientRect();return Math.max(0,-b.top,b.bottom-innerHeight,-b.left,b.right-innerWidth,e.scrollHeight-e.clientHeight-1,e.scrollWidth-e.clientWidth-1)});
const elementOverflows=required.map((e,i)=>({class:e.className,overflow:over[i],scroll:e.scrollHeight,client:e.clientHeight,rect:e.getBoundingClientRect().toJSON()})).filter(e=>e.overflow>1);
const scrolling=[...root.querySelectorAll('*')].filter(e=>/auto|scroll/.test(getComputedStyle(e).overflowY)&&e.scrollHeight>e.clientHeight+1).map(e=>e.className),s=getComputedStyle(root.querySelector('.player-story-text'));
const textRows=required.filter(e=>e.matches('.player-story-text,.player-choice-text,.player-choice-state,.player-vote-count')).map(e=>{const s=getComputedStyle(e);return{base:s.getPropertyValue('--surface-bg').trim(),foreground:s.color,shadow:s.textShadow,weight:s.fontWeight}});
const canvas=document.createElement('canvas');canvas.width=1000;canvas.height=100;const ctx=canvas.getContext('2d');const ink=font=>{ctx.clearRect(0,0,1000,100);ctx.font=font;ctx.fillText('SHOUG LONDON CHOOSE TO VOTE',0,65);return ctx.getImageData(0,0,1000,100).data.reduce((sum,v,i)=>sum+(i%4===3?v:0),0)};const oldInk=ink('700 36px Arial, sans-serif'),newInk=ink('900 36px '+s.fontFamily);
return{textRows,oldInk,newInk,elementOverflows,documentOverflow:Math.max(0,document.documentElement.scrollHeight-innerHeight),horizontalOverflow:Math.max(0,document.documentElement.scrollWidth-innerWidth),rootOverflow:Math.max(0,root.scrollHeight-root.clientHeight),maxElementOverflow:Math.max(...over),scrolling,bands,fontFamily:s.fontFamily,fontWeight:s.fontWeight,fontSize:s.fontSize,density:root.dataset.shougDensity,meta:document.querySelector('meta[name="theme-color"]').content,choices:[...root.querySelectorAll('.shoug-choice')].map(e=>e.getBoundingClientRect().height)};});
if(type===chromium&&results.length===0){const c=await context.newCDPSession(page);await c.send('DOM.enable');await c.send('CSS.enable');const d=await c.send('DOM.getDocument');const q=await c.send('DOM.querySelector',{nodeId:d.root.nodeId,selector:'.player-story-text'});audit.platformFonts=(await c.send('CSS.getPlatformFontsForNode',{nodeId:q.nodeId})).fonts;await c.detach();}
results.push({engine:type.name(),device,key,locked,...audit});const evidence=JSON.stringify(results.at(-1));
assert.equal(audit.documentOverflow,0,evidence);assert.equal(audit.horizontalOverflow,0,evidence);assert.ok(audit.rootOverflow<=1,evidence);assert.ok(audit.maxElementOverflow<=1,evidence);assert.equal(audit.scrolling.length,0);for(const row of audit.textRows){const dark=['#102f24','#62283d','#141514'];const light=['#e0fff0','#e3afbe','#ffffff'];const opposite=dark.includes(row.base)?light:dark;const css=h=>'rgb('+h.slice(1).match(/../g).map(v=>Number.parseInt(v,16)).join(', ')+')';assert.ok(opposite.map(css).includes(row.foreground),JSON.stringify(row));const shadowColors=(light.includes(row.base)?light:dark).map(css);assert.ok(shadowColors.some(c=>row.shadow.includes(c)),JSON.stringify(row));assert.equal(row.weight,'900');}assert.equal(audit.fontWeight,'900');assert.ok(audit.choices.every(h=>h>=44));
if(!n.is_end)assert.deepEqual(audit.bands.map(e=>e.band),Array.from({length:n.choices.length+3},(_,i)=>i%2?'A':'B'));
}}await context.close();}await browser.close();}
fs.writeFileSync(process.env.SHOUG_RESULTS||'/tmp/shoug-screen-results.json',JSON.stringify(results,null,2));console.log(JSON.stringify({checks:results.length,maxDocumentOverflow:Math.max(...results.map(r=>r.documentOverflow)),maxRootOverflow:Math.max(...results.map(r=>r.rootOverflow)),maxElementOverflow:Math.max(...results.map(r=>r.maxElementOverflow)),minimumChoice:Math.min(...results.flatMap(r=>r.choices)),font:results[0].fontFamily,platformFonts:results[0].platformFonts,weight:results[0].fontWeight,densities:[...new Set(results.map(r=>r.density))],nodes:[...keys]},null,2));
}finally{server.close();}})().catch(e=>{console.error(e);process.exit(1)});
